### ISSUE TITLE
TableViewDragger.swift:279:18: 'dynamic' instance method 'panGestureAction' must also be '@objc'

### ISSUE THREAD

**Issue by rajeshbeats** [KyoheiG3/TableViewDragger#13]
Build error after installing  TableViewDragger
<img width="1017" alt="screen shot 2018-02-24 at 3 03 10 pm" src="https://user-images.githubusercontent.com/1560365/36625452-db21e8f8-1973-11e8-8f65-da30fc4fd0a3.png">

**Comment by KyoheiG3** [comment]
Hi @rajeshbeats 
What's version of Library did you use? It looks old. Please, should use the latest version.

**Comment by rajeshbeats** [comment]
@KyoheiG3 I forget the version I used, but yea it is fixed when i updated the pods.
Thank you.
